# Generated by Django 5.1.5 on 2025-02-19 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greencredit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credito',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creditos', to='greencredit.cliente'),
        ),
    ]
