# Generated by Django 5.1.5 on 2025-02-19 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('greencredit', '0002_alter_credito_cliente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='cpf',
            new_name='bi',
        ),
    ]
